In [1]:
import pandas as pd
import numpy as np

Opening_cvs files

In [2]:
df = pd.read_csv('aug_train.csv')
df.head()

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0

#Sep Parameter

In [ ]:
#yahan ek tsc file load karengy per wo shi se data fetch nhi ker paegi tw hum function k ander sep use karengy q k tsv mei data tab se seperated hota tw 
pd.read_csv('movie_titles_metadata.tsv' , sep='\t')
#Error : columns ka naam nhi hai first row he column bangya hai tw hum khud se ek ;ist pass ker sakty hain

,m0,10 things i hate about you,1999,6.9,62847,['comedy' 'romance']
0,m1,1492: conquest of paradise,1992,6.2,10421,['adventure' 'biography' 'drama' 'history']
1,m2,15 minutes,2001,6.1,25854,['action' 'crime' 'drama' 'thriller']
2,m3,2001: a space odyssey,1968,8.4,163227,['adventure' 'mystery' 'sci-fi']
3,m4,48 hrs.,1982,6.9,22289,['action' 'comedy' 'crime' 'drama' 'thriller']
4,m5,the sum of all fears,1966,6.8,198939,['war' 'drama']
...,...,...,...,...,...,...
611,m612,watchmen,2009,7.8,135229,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
612,m613,xxx,2002,5.6,53505,['action' 'adventure' 'crime']
613,m614,x-men,2000,7.4,122149,['action' 'sci-fi']
614,m615,young frankenstein,1974,8.0,57618,['comedy' 'sci-fi']
615,m616,zulu dawn,1979,6.4,1911,['action' 'adventure' 'drama' 'history' 'war']

In [5]:

#Error : columns ka naam nhi hai first row he column bangya hai tw hum khud se ek ;ist pass ker sakty hain
pd.read_csv('movie_titles_metadata.tsv' , sep='\t', names=['S_no', 'Name', 'Year_of_Release', 'Rating', 'Votes', 'Genre'])

,S_no,Name,Year_of_Release,Rating,Votes,Genre
0,m0,10 things i hate about you,1999,6.9,62847,['comedy' 'romance']
1,m1,1492: conquest of paradise,1992,6.2,10421,['adventure' 'biography' 'drama' 'history']
2,m2,15 minutes,2001,6.1,25854,['action' 'crime' 'drama' 'thriller']
3,m3,2001: a space odyssey,1968,8.4,163227,['adventure' 'mystery' 'sci-fi']
4,m4,48 hrs.,1982,6.9,22289,['action' 'comedy' 'crime' 'drama' 'thriller']
...,...,...,...,...,...,...
612,m612,watchmen,2009,7.8,135229,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
613,m613,xxx,2002,5.6,53505,['action' 'adventure' 'crime']
614,m614,x-men,2000,7.4,122149,['action' 'sci-fi']
615,m615,young frankenstein,1974,8.0,57618,['comedy' 'sci-fi']
616,m616,zulu dawn,1979,6.4,1911,['action' 'adventure' 'drama' 'history' 'war']

Index_Col parameter

In [6]:
pd.read_csv('aug_train.csv')

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,32036,city_16,0.898,Male,No relevent experience,no_enrollment,Graduate,STEM,1,50-99,Pvt Ltd,1,12,0.0
153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,45,0.0
154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,1,60,0.0
155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,22,0.0
156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,1,18,0.0

In [7]:
# hum column ko index column bana sakty hai 
pd.read_csv('aug_train.csv', index_col='enrollee_id')

,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
enrollee_id,,,,,,,,,,,,,
8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
32036,city_16,0.898,Male,No relevent experience,no_enrollment,Graduate,STEM,1,50-99,Pvt Ltd,1,12,0.0
7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,45,0.0
31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,1,60,0.0
24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,22,0.0
5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,1,18,0.0

Header Parameter

In [8]:
pd.read_csv('test.csv')

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,0,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
1,1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,152,32036,city_16,0.898,Male,No relevent experience,no_enrollment,Graduate,STEM,1,50-99,Pvt Ltd,1,12,0.0
153,153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,45,0.0
154,154,31398,city_103,0.92,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,1,60,0.0
155,155,24576,city_103,0.92,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,22,0.0
156,156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,1,18,0.0

In [10]:
# unnamed column
pd.read_csv('test.csv', header=1) # ab firt row jjo hai columns ka naam banjaegi

,0,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
1,2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
2,3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
3,4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
4,5,7297,city_40,0.817,Male,Has relevent experience,Full time course,Masters,NaN,2,50-99,NaN,never,120,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,32036,city_16,0.898,Male,No relevent experience,no_enrollment,Graduate,STEM,1,50-99,Pvt Ltd,1,12,0.0
152,153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,45,0.0
153,154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,1,60,0.0
154,155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,22,0.0
155,156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,1,18,0.0

use_col Parameter

In [11]:
pd.read_csv('aug_train.csv')

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,32036,city_16,0.898,Male,No relevent experience,no_enrollment,Graduate,STEM,1,50-99,Pvt Ltd,1,12,0.0
153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,45,0.0
154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,1,60,0.0
155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,22,0.0
156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,1,18,0.0

In [15]:
#selected columns only fetch
pd.read_csv('aug_train.csv', usecols=['enrollee_id', 'gender', 'education_level'])

     enrollee_id gender education_level
0           8949   Male        Graduate
1          29725   Male        Graduate
2          11561    NaN        Graduate
3          33241    NaN        Graduate
4            666   Male         Masters
..           ...    ...             ...
152        32036   Male        Graduate
153         7386   Male        Graduate
154        31398   Male        Graduate
155        24576   Male        Graduate
156         5756   Male     High School

[157 rows x 3 columns]

Skip_rows/n_rows

In [18]:
# skip row mein particular row ko remove kersakty ho 
pd.read_csv('aug_train.csv', skiprows=[0,1])
# zarori nhi line wise nhumber do

,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
0,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
1,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
2,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
3,7297,city_40,0.817,Male,Has relevent experience,Full time course,Masters,NaN,2,50-99,NaN,never,120,0.0
4,1740,city_7,0.541,Other,Has relevent experience,no_enrollment,Graduate,STEM,<1,500-999,NaN,1,143,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,32036,city_16,0.898,Male,No relevent experience,no_enrollment,Graduate,STEM,1,50-99,Pvt Ltd,1,12,0.0
151,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,45,0.0
152,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,1,60,0.0
153,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,22,0.0
154,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,1,18,0.0

In [ ]:
pd.read_csv('aug_train.csv', nrows=100)
# ye restrict kerdeta hai rows ko jitni apko chahyeye ho

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,23211,city_162,0.642,Other,Has relevent experience,no_enrollment,High School,NaN,18,10/49,Pvt Ltd,3,149,0.0
96,1367,city_97,0.527,Female,Has relevent experience,no_enrollment,Graduate,STEM,3,NaN,Pvt Ltd,2,203,1.0
97,22251,city_28,0.610,Male,Has relevent experience,no_enrollment,Graduate,STEM,11,<10,Other,3,76,0.0
98,9598,city_75,0.540,Female,Has relevent experience,Full time course,Graduate,NaN,20,50-99,Funded Startup,>4,230,0.0
99,21182,city_97,0.517,Male,Has relevent experience,no_enrollment,Masters,Humanities,11,50-99,NaN,1,30,0.0

dtypes parameters

In [ ]:
pd.read_csv('aug_train.csv' dtype={'traget':int})

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,32036,city_16,0.898,Male,No relevent experience,no_enrollment,Graduate,STEM,1,50-99,Pvt Ltd,1,12,0.0
153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,45,0.0
154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,1,60,0.0
155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,22,0.0
156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,1,18,0.0

Handling Dates

In [ ]:
# Dates ko string se float ya number mein convert
#hamry pass abhi dates wala column nhi per mein uska code likh raha hon 
pd.read_csv('aug_train.csv', parse_date=['date'])